# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: true

jdk:
- openjdk11

services:
- postgresql

before_install:
  - psql -c 'create database cars;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="e5ea4254-a37a-4bcf-b6ef-8d25c83a5ac5"

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка   упала
notifications:
  email:
    recipients:
      - telesyn73@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
