# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: true

jdk:
- openjdk13

services:
- postgresql

before_install:
  - psql -c 'create database cars;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="1e836ccd-df7f-4b14-ba80-996c04464519"

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка   упала
notifications:
  email:
    recipients:
      - telesyn73@mail.ru
    on_success: never # default: change
    on_failure: never # default: always
